name=PeerDuino
version=1.0.0
author=Leonardo Groos Lago
maintainer=Leonardo Groos Lago
sentence=Protocolo ARQ Stop-and-Wait para comunicacao serial entre Arduinos.
paragraph=Implementa deteccao de erros por CRC-16, delimitacao por byte stuffing, maquina de estados Stop-and-Wait ARQ com retransmissoes e tipagem de dados (byte, word, float, data) entre Arduinos (ATmega328P).
category=Communication
url=https://github.com/GroosL/PeerDuino
architectures=*
includes=PeerDuino.h
